sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dnanusevski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dnanusevski/react-test npm test

after_success:
  - docker build -t dnanusevski/multi-client ./client
  - docker build -t dnanusevski/multi-nginx ./nginx
  - docker build -t dnanusevski/multi-server ./server
  - docker build -t dnanusevski/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dnanusevski/multi-client
  - docker push dnanusevski/multi-nginx
  - docker push dnanusevski/multi-server
  - docker push dnanusevski/multi-worker


deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"  
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-eu-central-1-405039439657"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_KEY" 